apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: banking
  template:
    metadata:
      labels:
        app: banking
    spec:
      containers:
        - name: banking
          image: ashwiniboddu/banking:latest
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: banking-volume
              mountPath: /data
          volumes:
            - name: banking-volume
              persistentVolumeClaim:
                claimName: banking-pvc
