apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: banking-pvc
  namespace: deployment  # 👈 required!
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 15Gi
